export const tsConfig = {
    $schema: "https://json.schemastore.org/tsconfig",
    compilerOptions: {
        composite: false,
        declaration: true,
        declarationMap: true,
        esModuleInterop: true,
        forceConsistentCasingInFileNames: true,
        inlineSources: false,
        isolatedModules: true,
        module: "nodenext",
        moduleResolution: "nodenext",
        noUncheckedIndexedAccess: true,
        noUnusedLocals: false,
        noUnusedParameters: false,
        outDir: "dist",
        preserveWatchOutput: true,
        rootDir: "./src",
        skipLibCheck: true,
        strict: true,
        target: "ES2022",
        types: ["node"],
    },
    include: ["src"],
    exclude: ["dist", "node_modules"],
};
