packages:
  - apps/*
  - packages/*
allowBuilds:
  "@tuler/node-libcmt": true
  es5-ext: true
  esbuild: true
catalog:
  "@biomejs/biome": "2.5.0"
minimumReleaseAgeExclude:
  - "@tuler/node-libcmt"
  - viem@2.53.1
onlyBuiltDependencies:
  - bufferutil
  - esbuild
  - sharp
  - utf-8-validate
